environment: production
chdir: /home/kleber/apps/ruby/Rock_Paper_or_Scissors_Game/current
address: 127.0.0.1
user: kleber
group: kleber
port: 3333
pid: /home/kleber/apps/ruby/Rock_Paper_or_Scissors_Game/current/tmp/thin.pid
rackup: /home/kleber/apps/ruby/Rock_Paper_or_Scissors_Game/current/config.ru
log: /home/kleber/apps/ruby/Rock_Paper_or_Scissors_Game/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false